### ISSUE TITLE
The results like yellow clouds

### ISSUE THREAD

**Issue by junshengzhou** [eladrich/latent-nerf#18]
Hi,
Thanks for sharing your great work! I find for a lot of prompts, the results look like yellow clouds without rich colors , for example "a lion":
![image](https://user-images.githubusercontent.com/45631941/211456614-1526b89d-e3b7-4558-a46f-8dc7fae391a6.png)
Do you have any idea on how to solve this problem? Thanks for your time!

**Comment by Jainam213** [comment]
Hey there i might be able to help on how to solve it
but can you pls help where can i find the trained model
it just gives me 
```
evaluating and saving model
done
```

Ill look into how to get better colors

**Comment by thuwzy** [comment]
It seems like you have used shadings? I tried shadings and got the same results as you.

**Comment by junshengzhou** [comment]
Hi,
Thanks for your remind! I will have a try. And if you turn of shading, will you get the correct results?

**Comment by thuwzy** [comment]
Yes, the results are correct

**Comment by junshengzhou** [comment]
I see. Thanks for you help!!

**Comment by chengmengli06** [comment]
how to turn off shading?
