### ISSUE TITLE
Conda environment

### ISSUE THREAD

**Issue by NiluK** [eladrich/latent-nerf#19]
Is there a specific conda environment that's able to be provided? Getting errors on a p3.2xl which is what the V100 is on an aws EC2

**Comment by NiluK** [comment]
Ok I managed to get it working on ubuntu 22.04

- Use python=3.8
- Install CUDA like normal (don't use 12, use 11.7)
- Remove the pytorch and torcvision hard dependencies 
- pip install imageio[ffmpeg] and imageio[pyav]
- export IGNORE_TORCH_VER=1

That should do it for latent-paint.

Will test out latent nerf.

**Comment by NiluK** [comment]
Yep latent nerf works fine with this too

**Comment by mshooter** [comment]
@NiluK  could you please provide the commands you did? 
I tried to do the way you said but it doesn't seem to work for me

**Comment by NiluK** [comment]
@mshooter can't help you here besides that tbh, I've moved on to using TEXTure, which is current SOTA

**Comment by flow-specter** [comment]
> 

I used cuda 11.3, and it doesn't work. I can't compile raymarching module successfully, can you give me some advice?
